# Generated by Django 4.2.4 on 2023-08-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_startingbid_listing_startingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='artist',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
