# Generated by Django 4.2.4 on 2023-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_watched_remove_watchlist_watcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
